//! Render the desired model into the three artifacts apply loads:
//!   * the Squid drop-in fragment (/etc/squid/conf.d/quartzfire-ssl-inspection.conf),
//!   * the do-not-inspect (splice) domain file Squid's `ssl::server_name` acl reads,
//!   * the nftables ruleset for the dedicated `qz_ssl` table (transparent
//!     redirect of in-scope 443 → the intercept port, plus the CA-download
//!     reachability guard).
//!
//! Pure string production — no I/O — so the whole thing is golden-tested.

use crate::ca;
use crate::model::{ContentFilter, Model};

/// The shipped exclusion baseline: categories that break under interception or
/// raise compliance concerns. Applied on top of the user list unless the admin
/// turns `default_exclusions` off. `.suffix` means "this domain and any
/// subdomain". Deliberately conservative — banking/finance, healthcare,
/// government, and known cert-pinned/update endpoints.
pub const DEFAULT_NO_INSPECT: &[&str] = &[
    // Cert-pinned / vendor update & telemetry that break when bumped.
    ".mozilla.org",
    ".mozilla.net",
    ".windowsupdate.com",
    ".update.microsoft.com",
    ".apple.com",
    ".mzstatic.com",
    ".googleapis.com",
    ".gvt1.com",
    ".android.com",
    // Banking / finance (illustrative anchors; admins extend per region).
    ".chase.com",
    ".bankofamerica.com",
    ".wellsfargo.com",
    ".paypal.com",
    // Healthcare / government (compliance).
    ".hhs.gov",
    ".irs.gov",
    ".va.gov",
];

/// The full ordered splice list written to no-inspect.txt: the baseline (when
/// enabled) followed by user entries, de-duplicated, order preserved.
pub fn no_inspect_list(model: &Model) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut push = |d: &str| {
        let d = d.trim();
        if !d.is_empty() && !out.iter().any(|e| e == d) {
            out.push(d.to_string());
        }
    };
    if model.default_exclusions {
        for d in DEFAULT_NO_INSPECT {
            push(d);
        }
    }
    for d in &model.no_inspect {
        push(d);
    }
    out
}

/// The `ssl::server_name` file body (one pattern per line, trailing newline).
pub fn no_inspect_file(model: &Model) -> String {
    let mut s = String::from("# QuartzFire SSL Inspection — do-not-inspect (spliced) domains.\n");
    s.push_str("# Generated by qzssl; edit via the WebUI, not by hand.\n");
    for d in no_inspect_list(model) {
        s.push_str(&d);
        s.push('\n');
    }
    s
}

/// The ICAP adaptation block — emitted ONLY when a content filter is
/// configured (default: absent). Because Squid bumps BEFORE adaptation, the
/// ICAP engine receives already-decrypted plaintext HTTP: that is the whole
/// reason e2guardian (or c-icap/ClamAV) does NOT need — and must NOT have — its
/// own TLS layer. Endpoint host/port/service names come from config, never
/// hardcoded, so any engine is a drop-in.
fn icap_block(cf: &ContentFilter) -> String {
    // fail-closed ⇒ bypass=off: if the filter is enabled and its ICAP service
    // is down, traffic must fail closed, not silently pass uninspected.
    let bypass = if cf.fail_closed() { "off" } else { "on" };
    format!(
        "\n# ── Content-filter adaptation (ICAP) ────────────────────────────────\n\
         # Squid bumps first, so the engine below receives PLAINTEXT HTTP. Any\n\
         # attached engine (e2guardian ICAP-mode / c-icap+ClamAV) is a pure\n\
         # filtering consumer — it must never do TLS MITM or hold a CA.\n\
         icap_enable on\n\
         icap_preview_enable on\n\
         icap_preview_size 1024\n\
         icap_send_client_ip on\n\
         icap_send_client_username off\n\
         # e2guardian is STATEFUL REQMOD→RESPMOD: it stamps an X-ICAP-E2G header\n\
         # on the REQMOD reply and rejects any RESPMOD lacking it (\"418 Bad\n\
         # composition\"). Share it across the master transaction, else every\n\
         # allowed site dies on RESPMOD with ERR_ICAP_FAILURE. Proven in\n\
         # tests/e2guardian-icap. Harmless for engines that don't set it.\n\
         adaptation_masterx_shared_names X-ICAP-E2G\n\
         icap_service qf_filter_req reqmod_precache icap://{host}:{port}/{req} bypass={bypass}\n\
         icap_service qf_filter_resp respmod_precache icap://{host}:{port}/{resp} bypass={bypass}\n\
         adaptation_access qf_filter_req allow all\n\
         adaptation_access qf_filter_resp allow all\n",
        host = cf.icap_host,
        port = cf.icap_port,
        req = cf.reqmod_service,
        resp = cf.respmod_service,
        bypass = bypass,
    )
}

/// The Squid drop-in fragment. Transparent interception: `https_port …
/// intercept ssl-bump` (clients configure no proxy — the nft redirect steers
/// their 443 here). Peek at step 1 to read SNI, splice the do-not-inspect
/// domains, bump everything else.
pub fn squid_fragment(model: &Model) -> String {
    let mut s = String::new();
    s.push_str("# QuartzFire SSL Inspection — generated by qzssl. Do not edit by hand.\n");
    s.push_str("# Squid is the SOLE TLS terminator on this box (owns ssl_bump, the CA,\n");
    s.push_str("# the private key, and the generated-cert store). See design.md.\n\n");

    if !model.enabled {
        s.push_str("# SSL inspection is disabled — no interception configured.\n");
        return s;
    }

    let intercept = model.intercept_port;
    s.push_str(&format!(
        "https_port {intercept} intercept ssl-bump \\\n    \
         name=qz_ssl_intercept \\\n    \
         generate-host-certificates=on \\\n    \
         dynamic_cert_mem_cache_size=8MB \\\n    \
         tls-cert={crt} \\\n    \
         tls-key={key}\n\n",
        crt = ca::CA_CRT,
        key = ca::CA_KEY,
    ));

    s.push_str(&format!(
        "sslcrtd_program {certgen} -s {db} -M 8MB\n",
        certgen = crate::apply::SECURITY_FILE_CERTGEN,
        db = crate::apply::SSL_DB_DIR,
    ));
    s.push_str("sslcrtd_children 5\n\n");

    // Upstream (origin) certificate validation. Block invalid upstream certs by
    // default; `upstream-invalid allow` relaxes to log-and-continue.
    if model.upstream_invalid == "allow" {
        s.push_str("# upstream-invalid allow: do not reject origins with bad certs.\n");
        s.push_str("tls_outgoing_options flags=DONT_VERIFY_PEER\n\n");
    } else {
        s.push_str("# upstream-invalid block (default): reject origins whose cert fails.\n");
        s.push_str("tls_outgoing_options default-ca=on\n\n");
    }

    s.push_str("acl step1 at_step SslBump1\n");
    s.push_str(&format!(
        "acl noInspect ssl::server_name \"{}\"\n\n",
        crate::apply::NO_INSPECT_FILE
    ));

    // Permit the intercepted traffic. The stock Debian squid.conf ships with
    // `http_access allow localnet` COMMENTED OUT and `http_access deny all` as
    // its final rule, so without an explicit allow here every bumped request
    // dies on the default deny ("access control configuration prevents your
    // request"). The conf.d include sits above that http_access section, so
    // this scoped allow is evaluated first. Scope it to the intercept port
    // (myportname) rather than `allow all`, so this drop-in can only ever
    // widen access for traffic the nft redirect steered here — never for any
    // other Squid listener that might exist on the box.
    s.push_str("acl qz_ssl_intercepted myportname qz_ssl_intercept\n");
    s.push_str("http_access allow qz_ssl_intercepted\n\n");

    s.push_str("ssl_bump peek step1\n");
    s.push_str("ssl_bump splice noInspect\n");
    if model.default_action == "splice" {
        s.push_str("# default-action splice: only explicitly-selected traffic is bumped.\n");
        s.push_str("ssl_bump splice all\n");
    } else {
        s.push_str("ssl_bump bump all\n");
    }

    // Log bump/splice decisions for the SIEM pipeline (ELK/Splunk).
    s.push_str("\n# SIEM: log every step so bump/splice decisions are auditable.\n");
    s.push_str(
        "logformat qzssl %ts.%03tu %>a %ssl::>sni %ssl::bump_mode %Ss/%03>Hs %<st %rm %ru\n",
    );
    s.push_str("access_log syslog:local4.info qzssl\n");

    if let Some(cf) = &model.content_filter {
        s.push_str(&icap_block(cf));
    } else {
        s.push_str(
            "\n# No content-filter engine attached (ICAP seam idle). This is where a\n\
             # future e2guardian/c-icap layer plugs in — see design.md.\n",
        );
    }

    s
}

/// Scope a replicated rule match to TLS: only tcp/443 is steered into Squid.
/// If the rule already constrains a destination port, trust it as-is; otherwise
/// append `tcp dport 443` (and for a match-everything rule, that IS the match).
fn steer_match(expr: &str) -> String {
    if expr.contains("dport") {
        expr.to_string()
    } else if expr.is_empty() {
        "tcp dport 443".to_string()
    } else {
        format!("{expr} tcp dport 443")
    }
}

/// The nftables ruleset for the dedicated `qz_ssl` table. Two jobs, both kept
/// OUT of vyos_filter (which VyOS regenerates wholesale on every commit — the
/// QuartzFire coexistence rule):
///   1. per-rule transparent steering: for each enabled inspection policy,
///      replicate its firewall rule's match (in `matches`, keyed by rule
///      number) and redirect matching tcp/443 to the intercept port. `splice`
///      policies render as explicit `return` carve-outs BEFORE the inspects.
///      A global `fib daddr type local return` spares box-local 443 (the WebUI)
///      so a LAN client reaching the firewall itself is never DNAT'd into Squid.
///   2. CA-download guard: the :4126 listener binds all interfaces, so this
///      drops it everywhere EXCEPT the trusted CA-download interfaces (`ca_scope`).
/// A disabled model renders an empty (table-flushing) ruleset.
///
/// `matches`: rule number → replicated match expression, or None for a policy
/// whose rule is gone/unreplicable (skipped here, surfaced via status.json).
/// `ca_scope`: the effective CA-download interfaces (apply derives this).
pub fn nft_ruleset(
    model: &Model,
    matches: &std::collections::BTreeMap<u32, Option<String>>,
    ca_scope: &[String],
) -> String {
    let mut s = String::new();
    s.push_str("# QuartzFire SSL Inspection — qz_ssl table. Generated by qzssl.\n");
    // Idempotent replace: create-then-flush guarantees the table exists before
    // we redefine it, and never leaves a half-state.
    s.push_str("add table inet qz_ssl\n");
    s.push_str("flush table inet qz_ssl\n");

    if !model.enabled {
        s.push_str("delete table inet qz_ssl\n");
        return s;
    }

    let ifset = |ifs: &[String]| -> String {
        ifs.iter()
            .map(|i| format!("\"{i}\""))
            .collect::<Vec<_>>()
            .join(", ")
    };

    // 1) Per-rule redirect: dstnat prerouting, driven by the bound firewall rules.
    s.push_str("table inet qz_ssl {\n");
    s.push_str("    chain prerouting {\n");
    s.push_str("        type nat hook prerouting priority dstnat; policy accept;\n");
    // Box-local 443 (the WebUI) is always spared, before any redirect.
    s.push_str("        fib daddr type local return\n");
    // splice carve-outs first, then inspects — each pass in policy (rule) order.
    for action in ["splice", "inspect"] {
        for policy in &model.policies {
            if !policy.enabled || policy.action != action {
                continue;
            }
            let Some(Some(expr)) = matches.get(&policy.rule) else { continue };
            let steer = steer_match(expr);
            if action == "splice" {
                s.push_str(&format!("        {steer} return\n"));
            } else {
                s.push_str(&format!(
                    "        {steer} redirect to :{port}\n",
                    port = model.intercept_port,
                ));
            }
        }
    }
    s.push_str("    }\n");

    // 2) CA-download reachability guard: drop :4126 except on trusted ifaces.
    s.push_str("    chain input {\n");
    s.push_str("        type filter hook input priority filter - 5; policy accept;\n");
    if ca_scope.is_empty() {
        // No trusted scope ⇒ do not expose the plaintext CA page anywhere.
        s.push_str("        tcp dport 4126 drop\n");
    } else {
        s.push_str(&format!(
            "        tcp dport 4126 iifname != {{ {ifs} }} drop\n",
            ifs = ifset(ca_scope),
        ));
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ContentFilter, Policy};
    use std::collections::BTreeMap;

    fn policy(rule: u32, action: &str) -> Policy {
        Policy { rule, ruleset: "forward".into(), action: action.into(), enabled: true }
    }

    fn enabled() -> Model {
        Model {
            enabled: true,
            policies: vec![policy(20, "inspect")],
            ..Model::default()
        }
    }

    #[test]
    fn disabled_fragment_has_no_ports() {
        let s = squid_fragment(&Model::default());
        assert!(s.contains("disabled"));
        assert!(!s.contains("https_port"));
    }

    #[test]
    fn enabled_fragment_bumps_and_splices() {
        let s = squid_fragment(&enabled());
        assert!(s.contains("https_port 3129 intercept ssl-bump"));
        assert!(s.contains("name=qz_ssl_intercept"));
        // Without an explicit allow, bumped traffic dies on squid.conf's
        // default `http_access deny all` — the ERR_ACCESS_DENIED page.
        assert!(s.contains("acl qz_ssl_intercepted myportname qz_ssl_intercept"));
        assert!(s.contains("http_access allow qz_ssl_intercepted"));
        assert!(s.contains("ssl_bump peek step1"));
        assert!(s.contains("ssl_bump splice noInspect"));
        assert!(s.contains("ssl_bump bump all"));
        assert!(s.contains(ca::CA_CRT));
        // No ICAP block without a content filter.
        assert!(!s.contains("icap_enable"));
        assert!(s.contains("ICAP seam idle"));
    }

    #[test]
    fn default_action_splice_does_not_bump_all() {
        let m = Model { default_action: "splice".into(), ..enabled() };
        let s = squid_fragment(&m);
        assert!(s.contains("ssl_bump splice all"));
        assert!(!s.contains("ssl_bump bump all"));
    }

    #[test]
    fn icap_block_only_with_content_filter_and_fails_closed() {
        let mut m = enabled();
        m.content_filter = Some(ContentFilter::default());
        let s = squid_fragment(&m);
        assert!(s.contains("icap_enable on"));
        assert!(s.contains("icap://127.0.0.1:1344/request bypass=off"));
        assert!(s.contains("icap://127.0.0.1:1344/response bypass=off"));
        // e2guardian REQMOD→RESPMOD correlation header must be shared, else
        // allowed traffic dies on RESPMOD (proven in tests/e2guardian-icap).
        assert!(s.contains("adaptation_masterx_shared_names X-ICAP-E2G"));
    }

    #[test]
    fn icap_fail_open_flips_bypass() {
        let mut m = enabled();
        m.content_filter = Some(ContentFilter { fail_mode: "open".into(), ..ContentFilter::default() });
        let s = squid_fragment(&m);
        assert!(s.contains("bypass=on"));
    }

    #[test]
    fn icap_endpoint_from_config_not_hardcoded() {
        let mut m = enabled();
        m.content_filter = Some(ContentFilter {
            icap_host: "10.0.0.9".into(),
            icap_port: 1345,
            reqmod_service: "avscan".into(),
            respmod_service: "avscan".into(),
            fail_mode: "closed".into(),
        });
        let s = squid_fragment(&m);
        assert!(s.contains("icap://10.0.0.9:1345/avscan bypass=off"));
    }

    #[test]
    fn no_inspect_merges_defaults_and_user() {
        let mut m = enabled();
        m.no_inspect = vec!["internal.example".into(), ".mozilla.org".into()];
        let list = no_inspect_list(&m);
        assert!(list.contains(&".mozilla.org".to_string()));
        assert!(list.contains(&"internal.example".to_string()));
        // De-duplicated: .mozilla.org is in the baseline too.
        assert_eq!(list.iter().filter(|d| *d == ".mozilla.org").count(), 1);
    }

    #[test]
    fn no_inspect_defaults_can_be_dropped() {
        let m = Model { default_exclusions: false, no_inspect: vec!["only.this".into()], ..enabled() };
        let list = no_inspect_list(&m);
        assert_eq!(list, vec!["only.this".to_string()]);
    }

    #[test]
    fn nft_replicates_rule_match_and_guards_cadist() {
        let matches: BTreeMap<u32, Option<String>> =
            [(20u32, Some("iifname \"eth1\" ip saddr 10.0.0.0/8".to_string()))].into_iter().collect();
        let s = nft_ruleset(&enabled(), &matches, &["eth1".to_string()]);
        assert!(s.contains("table inet qz_ssl"));
        // Box-local 443 (e.g. the WebUI) is spared before any redirect.
        assert!(s.contains("fib daddr type local return"));
        // The rule's replicated match, scoped to tcp/443, redirected to Squid.
        assert!(s.contains("iifname \"eth1\" ip saddr 10.0.0.0/8 tcp dport 443 redirect to :3129"));
        assert!(
            s.find("fib daddr type local return").unwrap() < s.find("redirect to :3129").unwrap()
        );
        assert!(s.contains("tcp dport 4126 iifname != { \"eth1\" } drop"));
    }

    #[test]
    fn nft_splice_returns_before_inspect_redirects() {
        let m = Model {
            enabled: true,
            policies: vec![policy(20, "inspect"), policy(30, "splice")],
            ..Model::default()
        };
        let matches: BTreeMap<u32, Option<String>> = [
            (20u32, Some(String::new())),                       // match-everything inspect
            (30u32, Some("ip saddr 10.9.0.0/24".to_string())),  // splice carve-out
        ]
        .into_iter()
        .collect();
        let s = nft_ruleset(&m, &matches, &[]);
        // Splice (return) must precede the inspect (redirect).
        let splice = s.find("ip saddr 10.9.0.0/24 tcp dport 443 return").unwrap();
        let inspect = s.find("tcp dport 443 redirect to :3129").unwrap();
        assert!(splice < inspect);
        // Empty CA scope ⇒ the plaintext CA page is hidden everywhere.
        assert!(s.contains("tcp dport 4126 drop"));
    }

    #[test]
    fn nft_unresolved_policy_is_skipped() {
        // A policy whose match is None (dangling/unreplicable rule) emits nothing.
        let matches: BTreeMap<u32, Option<String>> = [(20u32, None)].into_iter().collect();
        let s = nft_ruleset(&enabled(), &matches, &[]);
        assert!(!s.contains("redirect to :3129"));
        // Table + guards still render.
        assert!(s.contains("fib daddr type local return"));
    }

    #[test]
    fn nft_disabled_deletes_table() {
        let s = nft_ruleset(&Model::default(), &BTreeMap::new(), &[]);
        assert!(s.contains("delete table inet qz_ssl"));
    }
}
